/* eslint-disable */
/* global WebImporter */
/** Parser for security-trust. Base: security-trust. Source: local draft feature-811-home. */
export default function parse(element, { document }) {
  // Convention: 1 column, 2 rows -> [name], [heading + description].
  // The animated "8‖" mark is generated by the block JS, so it is not authored.
  const rows = Array.from(element.children);

  // Collect element references from a static snapshot — createBlock moves them
  // into the table, so never loop on firstElementChild (that spins forever).
  const contentCell = [];
  rows.forEach((row) => {
    Array.from(row.children).forEach((cell) => {
      Array.from(cell.children).forEach((node) => contentCell.push(node));
    });
  });

  // empty-block guard
  if (contentCell.length === 0) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const cells = [[contentCell]]; // row 2: heading + description (single cell)

  const block = WebImporter.Blocks.createBlock(document, { name: 'Security Trust', cells });
  element.replaceWith(block);
}
